# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/library.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/library.proto\"3\n\x04\x42ook\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\x04\"\x1f\n\x0fGetBooksRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"R\n\x10GetBooksResponse\x12\x13\n\tall_books\x18\x01 \x01(\tH\x00\x12\x15\n\x03\x65rr\x18\x02 \x01(\x0b\x32\x06.ErrorH\x00\x42\x12\n\x10\x61ll_books_or_err\"(\n\x18GetReturnDeadlineRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"Q\n\x19GetReturnDeadlineResponse\x12\x0e\n\x04\x64\x61te\x18\x01 \x01(\tH\x00\x12\x15\n\x03\x65rr\x18\x02 \x01(\x0b\x32\x06.ErrorH\x00\x42\r\n\x0b\x64\x61te_or_err\"#\n\x13GetBookCountRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"X\n\x14GetBookCountResponse\x12\x14\n\nbook_count\x18\x01 \x01(\rH\x00\x12\x15\n\x03\x65rr\x18\x02 \x01(\x0b\x32\x06.ErrorH\x00\x42\x13\n\x11\x62ook_count_or_err\"&\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\r*=\n\tErrorCode\x12\x18\n\x14\x45RR_CODE_BAD_REQUEST\x10\x00\x12\x16\n\x12\x45RR_CODE_NOT_FOUND\x10\x01\x32\xc3\x01\n\x07Library\x12/\n\x08GetBooks\x12\x10.GetBooksRequest\x1a\x11.GetBooksResponse\x12J\n\x11GetReturnDeadline\x12\x19.GetReturnDeadlineRequest\x1a\x1a.GetReturnDeadlineResponse\x12;\n\x0cGetBookCount\x12\x14.GetBookCountRequest\x1a\x15.GetBookCountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=485
  _globals['_ERRORCODE']._serialized_end=546
  _globals['_BOOK']._serialized_start=23
  _globals['_BOOK']._serialized_end=74
  _globals['_GETBOOKSREQUEST']._serialized_start=76
  _globals['_GETBOOKSREQUEST']._serialized_end=107
  _globals['_GETBOOKSRESPONSE']._serialized_start=109
  _globals['_GETBOOKSRESPONSE']._serialized_end=191
  _globals['_GETRETURNDEADLINEREQUEST']._serialized_start=193
  _globals['_GETRETURNDEADLINEREQUEST']._serialized_end=233
  _globals['_GETRETURNDEADLINERESPONSE']._serialized_start=235
  _globals['_GETRETURNDEADLINERESPONSE']._serialized_end=316
  _globals['_GETBOOKCOUNTREQUEST']._serialized_start=318
  _globals['_GETBOOKCOUNTREQUEST']._serialized_end=353
  _globals['_GETBOOKCOUNTRESPONSE']._serialized_start=355
  _globals['_GETBOOKCOUNTRESPONSE']._serialized_end=443
  _globals['_ERROR']._serialized_start=445
  _globals['_ERROR']._serialized_end=483
  _globals['_LIBRARY']._serialized_start=549
  _globals['_LIBRARY']._serialized_end=744
# @@protoc_insertion_point(module_scope)
