# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import library_pb2 as proto_dot_library__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBooks = channel.unary_unary(
                '/Library/GetBooks',
                request_serializer=proto_dot_library__pb2.GetBooksRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.GetBooksResponse.FromString,
                _registered_method=True)
        self.GetReturnDeadline = channel.unary_unary(
                '/Library/GetReturnDeadline',
                request_serializer=proto_dot_library__pb2.GetReturnDeadlineRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.GetReturnDeadlineResponse.FromString,
                _registered_method=True)
        self.GetBookCount = channel.unary_unary(
                '/Library/GetBookCount',
                request_serializer=proto_dot_library__pb2.GetBookCountRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.GetBookCountResponse.FromString,
                _registered_method=True)


class LibraryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBooks(self, request, context):
        """What books are currently checked out
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReturnDeadline(self, request, context):
        """When are the books currently checked out due
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookCount(self, request, context):
        """How many books does the reader have checked out
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooks,
                    request_deserializer=proto_dot_library__pb2.GetBooksRequest.FromString,
                    response_serializer=proto_dot_library__pb2.GetBooksResponse.SerializeToString,
            ),
            'GetReturnDeadline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReturnDeadline,
                    request_deserializer=proto_dot_library__pb2.GetReturnDeadlineRequest.FromString,
                    response_serializer=proto_dot_library__pb2.GetReturnDeadlineResponse.SerializeToString,
            ),
            'GetBookCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookCount,
                    request_deserializer=proto_dot_library__pb2.GetBookCountRequest.FromString,
                    response_serializer=proto_dot_library__pb2.GetBookCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Library', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Library', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Library(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Library/GetBooks',
            proto_dot_library__pb2.GetBooksRequest.SerializeToString,
            proto_dot_library__pb2.GetBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReturnDeadline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Library/GetReturnDeadline',
            proto_dot_library__pb2.GetReturnDeadlineRequest.SerializeToString,
            proto_dot_library__pb2.GetReturnDeadlineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Library/GetBookCount',
            proto_dot_library__pb2.GetBookCountRequest.SerializeToString,
            proto_dot_library__pb2.GetBookCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
